import { NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import Event, { type IEvent } from "@/database/event.model";

type RouteParams = {
  params: Promise<{ slug: string }>;
};

type EventResponse = {
  message: string;
  event: IEvent;
};

type ErrorResponse = {
  message: string;
  error?: string;
};

// Matches URL-friendly slugs generated by the Event model.
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const isValidSlug = (slug: string): boolean =>
  slug.length > 0 && slug.length <= 200 && SLUG_PATTERN.test(slug);

export async function GET(
  _request: Request,
  { params }: RouteParams,
): Promise<NextResponse<EventResponse | ErrorResponse>> {
  try {
    const { slug } = await params;

    if (!slug?.trim()) {
      return NextResponse.json(
        { message: "Slug is required." },
        { status: 400 },
      );
    }

    const normalizedSlug = slug.trim().toLowerCase();

    if (!isValidSlug(normalizedSlug)) {
      return NextResponse.json(
        { message: "Invalid slug format." },
        { status: 400 },
      );
    }

    await connectDB();

    const event = await Event.findOne({ slug: normalizedSlug });

    if (!event) {
      return NextResponse.json(
        { message: "Event not found." },
        { status: 404 },
      );
    }

    return NextResponse.json(
      { message: "Event fetched successfully.", event },
      { status: 200 },
    );
  } catch (error) {
    console.error(error);

    return NextResponse.json(
      {
        message: "Failed to fetch event.",
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
